In [ ]:
%pip install pandas
import pandas as pd
import numpy as np
%pip install xlsxwriter

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 12.5 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9

In [ ]:
df1 = pd.read_excel("https://drive.usercontent.google.com/download?id=", index_col=0)

In [ ]:
df1.head()

,SKU,Content,Short Description
Title,,,
Malla Vidrio 30X30 Ocre A 0028,2009Oc,Formato:30x30mm<br>Dimension Mosaico (piezas):...,NaN
Malla Vidrio 30X30 Oc‚ano Gml 017,2009Oce,Formato:30x30mm<br> Dimension Mosaico (piezas...,NaN
Malla Mosaico Blue GMB-2342 4mm 30x30,2020Bl,"<h3><p style=""color:#d83030;""><b>Código Limatc...",NaN
"Cerámica Muro Blanco Brillo (Con Engobe) 20x30(1,5)",3115,"<h5 style=""color: #ff0000;""><span style=""color...",NaN
"Cerámica Muro Serrano Beige 25x35(2,22)",3205Be,"<h3><p style=""color:#ff0000;""><b>Código Limatc...",NaN

In [ ]:
df2 = df1.drop(['Short Description'], axis=1)
df2.head()

,SKU,Content
Title,,
Malla Vidrio 30X30 Ocre A 0028,2009Oc,Formato:30x30mm<br>Dimension Mosaico (piezas):...
Malla Vidrio 30X30 Oc‚ano Gml 017,2009Oce,Formato:30x30mm<br> Dimension Mosaico (piezas...
Malla Mosaico Blue GMB-2342 4mm 30x30,2020Bl,"<h3><p style=""color:#d83030;""><b>Código Limatc..."
"Cerámica Muro Blanco Brillo (Con Engobe) 20x30(1,5)",3115,"<h5 style=""color: #ff0000;""><span style=""color..."
"Cerámica Muro Serrano Beige 25x35(2,22)",3205Be,"<h3><p style=""color:#ff0000;""><b>Código Limatc..."

In [ ]:
# Modifica la columna 'Content' dentro del DataFrame df2, manteniendo otras columnas
df2['Content'] = df2['Content'].str.replace('<br>', '_').str.replace('<h3>', '_').str.replace('<b>', '_')
df2.head()

,SKU,Content
Title,,
Malla Vidrio 30X30 Ocre A 0028,2009Oc,Formato:30x30mm_Dimension Mosaico (piezas): 25...
Malla Vidrio 30X30 Oc‚ano Gml 017,2009Oce,Formato:30x30mm_ Dimension Mosaico (piezas): ...
Malla Mosaico Blue GMB-2342 4mm 30x30,2020Bl,"_<p style=""color:#d83030;"">_Código Limatco: 20..."
"Cerámica Muro Blanco Brillo (Con Engobe) 20x30(1,5)",3115,"<h5 style=""color: #ff0000;""><span style=""color..."
"Cerámica Muro Serrano Beige 25x35(2,22)",3205Be,"_<p style=""color:#ff0000;"">_Código Limatco: 32..."

In [ ]:
df2.index.str.contains("Porc.")
df2.head()

,SKU,Content
Title,,
Malla Vidrio 30X30 Ocre A 0028,2009Oc,Formato:30x30mm_Dimension Mosaico (piezas): 25...
Malla Vidrio 30X30 Oc‚ano Gml 017,2009Oce,Formato:30x30mm_ Dimension Mosaico (piezas): ...
Malla Mosaico Blue GMB-2342 4mm 30x30,2020Bl,"_<p style=""color:#d83030;"">_Código Limatco: 20..."
"Cerámica Muro Blanco Brillo (Con Engobe) 20x30(1,5)",3115,"<h5 style=""color: #ff0000;""><span style=""color..."
"Cerámica Muro Serrano Beige 25x35(2,22)",3205Be,"_<p style=""color:#ff0000;"">_Código Limatco: 32..."

In [ ]:
df2['PORC'] = df2.index.str.contains('Porc\\.')
df2.head()

,SKU,Content,PORC
Title,,,
Malla Vidrio 30X30 Ocre A 0028,2009Oc,Formato:30x30mm_Dimension Mosaico (piezas): 25...,False
Malla Vidrio 30X30 Oc‚ano Gml 017,2009Oce,Formato:30x30mm_ Dimension Mosaico (piezas): ...,False
Malla Mosaico Blue GMB-2342 4mm 30x30,2020Bl,"_<p style=""color:#d83030;"">_Código Limatco: 20...",False
"Cerámica Muro Blanco Brillo (Con Engobe) 20x30(1,5)",3115,"<h5 style=""color: #ff0000;""><span style=""color...",False
"Cerámica Muro Serrano Beige 25x35(2,22)",3205Be,"_<p style=""color:#ff0000;"">_Código Limatco: 32...",False

In [ ]:
import re

# Asegura de que la columna 'Content' sea string antes de limpiar y aplica la limpieza
df2['Content'] = df2['Content'].astype(str).apply(lambda x: re.sub(r'<.*?>', '', x))

# Guardar el DataFrame df2 (con la columna 'Content' limpia y todas las demás columnas) a Excel
df2.to_excel('PORC.xlsx', index=True)